FROM openjdk:8u282-jre
RUN mkdir /usr/local/test-ranch
ENV LANG C.UTF-8
COPY src /usr/local/test-ranch/src
#COPY target/test-ranch.jar /usr/local/test-ranch/test-ranch.jar
#CMD ["java","-Duser.timezone=GMT+08","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8787","-jar","/usr/local/test-ranch/test-ranch.jar"]